version: "3"
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: production
    expose:
      - "1337"
    command: npm run web
